# Generated by Django 3.1 on 2020-09-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20200918_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rank',
            field=models.IntegerField(choices=[(5, 'A'), (4, 'B'), (3, 'C'), (2, 'D'), (1, 'F')]),
        ),
    ]
